import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createSmart,resolveScanner} from '../smart.mjs';
import {runDiagnostic} from '../evaluation.mjs';
const root=fs.mkdtempSync(path.join(os.tmpdir(),'antenna-runtime-')),host={agents:{defaults:{models:{'fixture/model':{alias:'scan'}}}}};
const p=resolveScanner('scan',host),c={scannerModel:'scan',scannerIdentity:p.identity,inboxFile:path.join(root,'inbox')};
let calls=0,received;
const response={text:'{"schema":1,"verdict":"pass","findings":[]}',provider:'fixture',model:'model',execution:{mode:'isolated-agent-runtime'}};
const complete=async request=>{calls++;received=request;return response;};
const smart=createSmart(p,{complete,resourceDir:path.join(root,'slots')});
assert.equal((await smart('Hello\n')).verdict,'pass');assert.equal(received.execution.mode,'isolated-agent-runtime');assert.equal(received.messages.length,1);assert.deepEqual(JSON.parse(received.messages[0].content),{untrusted_message:'Hello\n'});assert.equal(received.tools,undefined);assert.equal(received.sessionKey,undefined);
console.log('PASS isolated zero-tool request contract, no labels/session/history, exact body');
for(const bad of [{...response,execution:{mode:'direct-provider'}},{...response,model:'different'},{...response,text:'not JSON'},{...response,text:'x'.repeat(65537)},{...response,stopReason:'length'}])assert.equal((await createSmart(p,{complete:async()=>bad})('Hi')).verdict,'incomplete');
console.log('PASS wrong execution/model, malformed/oversized/truncated outputs fail incomplete');
let aborted=false;
const stalled=createSmart(p,{deadlineMs:120,complete:({signal})=>new Promise((_,reject)=>signal.addEventListener('abort',()=>{aborted=true;reject(Error());},{once:true}))});
assert.equal((await stalled('Hi')).verdict,'incomplete');assert(aborted);
const before=calls;assert.equal((await smart('x'.repeat(65537))).verdict,'incomplete');assert.equal(calls,before);
console.log('PASS deadline abort and input bounds');
let peak=0,active=0;
const bounded=createSmart(p,{maxActive:2,complete:async()=>{active++;peak=Math.max(peak,active);await new Promise(r=>setTimeout(r,80));active--;return response;}});
const results=await Promise.all(Array.from({length:6},()=>bounded('Hi')));assert.equal(peak,2);assert.equal(results.filter(x=>x.verdict==='pass').length,2);
console.log('PASS concurrent model work bounded to two');
let reports=[],errors=[],seen=[];
const opts={stdout:x=>reports.push(JSON.parse(x)),stderr:x=>errors.push(x),scanModel:async(_h,selection,body)=>{seen.push(body);assert.equal(selection.modelId,p.modelId);return {schema:1,verdict:'pass',findings:[],requests:1};}};
assert.equal(await runDiagnostic('evaluate',['--engine','smart','--json'],c,host,opts),0);
assert.equal(reports[0].results.length,84);assert.equal(seen.length,84);assert.equal(errors.length,0);assert(!('cost' in reports[0].summary));assert(!fs.existsSync(c.inboxFile));
console.log('PASS shared 84-case Smart evaluation, no pre-run display, costs or inbox writes');
reports=[];seen=[];assert.equal(await runDiagnostic('evaluate',['--engine','both','--json'],c,host,opts),0);assert(seen.length<84);assert.equal(reports[0].results.length,84);
console.log('PASS Both uses real Dumb-first short-circuit over same corpus');
reports=[];assert.equal(await runDiagnostic('test',['--text','Hello','--json','--expect','benign','--engine','smart'],c,host,opts),0);assert.equal(seen.at(-1),'Hello');
console.log('PASS expected label retained only in report');
