import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {resolveScanner} from '../smart.mjs';
import {loadRuleset,validateRuleset} from '../ruleset.mjs';
import {scanDumb} from '../scanners.mjs';
const root=fs.mkdtempSync(path.join(os.tmpdir(),'antenna-rules-'));
const host={agents:{defaults:{models:{'fixture/model':{alias:'scan'}}}},models:{providers:{fixture:{api:'openai-completions',baseUrl:'http://localhost:1',apiKey:'first',models:[{id:'model'}]}}}};
const selection=resolveScanner('scan',host);assert.equal(selection.modelId,'fixture/model');
assert.throws(()=>resolveScanner('absent',host));
const rotated=structuredClone(host);rotated.models.providers.fixture.apiKey='second';assert.equal(resolveScanner('scan',rotated).identity,selection.identity);
rotated.models.providers.fixture.baseUrl='http://localhost:2';assert.notEqual(resolveScanner('scan',rotated).identity,selection.identity);
console.log('PASS registered alias selection, unknown refusal, credential rotation and route drift');
const good={formatVersion:1,rules:[{id:'ONE',pattern:'special marker',flags:'iu',explanation:'Fixture marker'}]},file=path.join(root,'rules.json');
fs.writeFileSync(file,JSON.stringify(good));const snapshot=loadRuleset(file);
for(const bad of [{...good,formatVersion:2},{...good,rules:[]},{...good,rules:[...good.rules,...good.rules]},{...good,rules:[{...good.rules[0],pattern:'('}]},{...good,rules:[{...good.rules[0],flags:'g'}]},{...good,rules:[{...good.rules[0],run:'code'}]}])assert.throws(()=>validateRuleset(bad));
assert.throws(()=>loadRuleset(path.join(root,'missing')));assert.throws(()=>loadRuleset('relative.json'));
fs.symlinkSync(file,path.join(root,'link'));assert.throws(()=>loadRuleset(path.join(root,'link')));
console.log('PASS rule schema, duplicates, regex, flags, executable fields, missing and symlink refusal');
assert.equal((await scanDumb('special marker',{ruleset:snapshot})).verdict,'flagged');
fs.writeFileSync(file,JSON.stringify({...good,rules:[{...good.rules[0],pattern:'different'}]}));
assert.equal((await scanDumb('special marker',{ruleset:snapshot})).verdict,'flagged');assert.equal((await scanDumb('special marker',{ruleset:loadRuleset(file)})).verdict,'pass');
assert.equal((await scanDumb('special marker',{ruleset:snapshot})).verdict,'flagged');
console.log('PASS immutable selection snapshot and pooled-worker ruleset isolation');
const evil={formatVersion:1,rules:[{id:'SLOW',pattern:'(a+)+$',flags:'u',explanation:'Timeout fixture'}]};fs.writeFileSync(file,JSON.stringify(evil));
assert.equal((await scanDumb('a'.repeat(5000)+'!',{ruleset:loadRuleset(file),deadlineMs:100})).verdict,'incomplete');
assert.equal((await scanDumb('special marker',{ruleset:snapshot})).verdict,'flagged');
console.log('PASS pathological user regex terminated and subsequent scanner recovered');
const cli=new URL('../cli.mjs',import.meta.url).pathname,cfg=path.join(root,'host.json'),policy=path.join(root,'policy.json');
fs.writeFileSync(cfg,JSON.stringify(host));fs.writeFileSync(policy,JSON.stringify({schemaVersion:2,receiver:'beta',bearer:'x'.repeat(32),peers:{},destinations:{},inboxFile:path.join(root,'inbox'),replayFile:path.join(root,'replay')}));
const run=(...args)=>spawnSync(process.execPath,[cli,cfg,...args],{encoding:'utf8'});
assert.equal(run('init',policy).status,0);assert.equal(run('mode','smart').status,1);
fs.writeFileSync(file,JSON.stringify(good));assert.equal(run('rules','validate',file).status,0);assert.equal(run('rules','select',file).status,0);
const saved=JSON.parse(fs.readFileSync(cfg));assert.equal(saved.plugins.entries.antenna.enabled,false);assert.equal(saved.plugins.entries.antenna.config.rulesetFile,file);assert.deepEqual(saved.models,host.models);
assert.equal(run('status').status,0);
console.log('PASS CLI initialization, unvalidated Smart refusal, rules validation/selection and status');
